-- Sep 24, 2013 2:49:01 PM VET
-- Get Weight from Scale
CREATE TABLE FTA_ScreenConfig (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, EndCharacter NUMERIC(10) DEFAULT NULL , FTA_ScreenConfig_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, PosEndCut NUMERIC(10) NOT NULL, PosEnd_SCut NUMERIC(10) NOT NULL, PosStartCut NUMERIC(10) NOT NULL, PosStart_SCut NUMERIC(10) NOT NULL, StartCharacter NUMERIC(10) NOT NULL, StrLength NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_ScreenConfig_Key PRIMARY KEY (FTA_ScreenConfig_ID))
;

-- Sep 24, 2013 2:49:09 PM VET
-- Get Weight from Scale
CREATE TABLE FTA_SerialPortConfig (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Bauds VARCHAR(6) DEFAULT '9600' NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DataBits CHAR(1) DEFAULT '8' NOT NULL, FlowControl CHAR(1) DEFAULT '1' NOT NULL, FTA_SerialPortConfig_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Parity CHAR(1) DEFAULT '0' NOT NULL, SerialPort VARCHAR(60) NOT NULL, StopBits VARCHAR(3) DEFAULT '1' NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_SerialPortConfig_Key PRIMARY KEY (FTA_SerialPortConfig_ID))
;

-- Sep 24, 2013 2:49:19 PM VET
-- Get Weight from Scale
CREATE TABLE FTA_WeightScale (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_ScreenConfig_ID NUMERIC(10) NOT NULL, FTA_SerialPortConfig_ID NUMERIC(10) NOT NULL, FTA_WeightScale_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_WeightScale_Key PRIMARY KEY (FTA_WeightScale_ID))
;

-- Sep 24, 2013 2:49:27 PM VET
-- Get Weight from Scale
CREATE TABLE FTA_WeightScale_Role (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Role_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_WeightScale_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_WeightScale_Role_Key PRIMARY KEY (AD_Role_ID, FTA_WeightScale_ID))
;

