ALTER TABLE FTA_WeightScale_Role ADD CONSTRAINT FK_FTA_WeightScale_Role_WeightScale FOREIGN KEY (FTA_WeightScale_ID)
REFERENCES FTA_WeightScale (FTA_WeightScale_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale_Role ADD CONSTRAINT FK_FTA_WeightScale_Role_Role FOREIGN KEY (AD_Role_ID)
REFERENCES AD_Role (AD_Role_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;


ALTER TABLE FTA_WeightScale_Role ADD CONSTRAINT FK_FTA_WeightScale_Role_Client FOREIGN KEY (AD_Client_ID)
REFERENCES AD_Client (AD_Client_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale_Role ADD CONSTRAINT FK_FTA_WeightScale_Role_Org FOREIGN KEY (AD_Org_ID)
REFERENCES AD_Org (AD_Org_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_Client FOREIGN KEY (AD_Client_ID)
REFERENCES AD_Client (AD_Client_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_Org FOREIGN KEY (AD_Org_ID)
REFERENCES AD_Org (AD_Org_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_SerialPortConfig FOREIGN KEY (FTA_SerialPortConfig_ID)
REFERENCES FTA_SerialPortConfig (FTA_SerialPortConfig_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_ScreenConfig FOREIGN KEY (FTA_ScreenConfig_ID)
REFERENCES FTA_ScreenConfig (FTA_ScreenConfig_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_UOM  FOREIGN KEY (C_UOM_ID)
REFERENCES C_UOM (C_UOM_ID) 
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_FTA_ScreenConfig FOREIGN KEY (FTA_ScreenConfig_ID)
	REFERENCES FTA_ScreenConfig(FTA_ScreenConfig_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;
ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_FTA_SerialPortConfig FOREIGN KEY (FTA_SerialPortConfig_ID)
	REFERENCES FTA_SerialPortConfig(FTA_SerialPortConfig_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;
ALTER TABLE FTA_WeightScale ADD CONSTRAINT FK_FTA_WeightScale_C_UOM FOREIGN KEY (C_UOM_ID)
	REFERENCES C_UOM(C_UOM_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;
ALTER TABLE FTA_WeightScale_Role ADD CONSTRAINT FK_FTA_WeightScale_Role_AD_Role FOREIGN KEY (AD_Role_ID)
	REFERENCES AD_Role(AD_Role_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;
ALTER TABLE FTA_WeightScale_Role ADD CONSTRAINT FK_FTA_WeightScale_Role_FTA_WeightScale FOREIGN KEY (FTA_WeightScale_ID)
	REFERENCES FTA_WeightScale(FTA_WeightScale_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;
